name: Espelhar LVGL sem refs de pull requests

on:
  schedule:
    - cron: '0 3 * * 0'  # Todo domingo às 03:00 UTC
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Clonar repositório LVGL com --mirror
        run: |
          git clone --mirror https://github.com/lvgl/lvgl.git lvgl-mirror

      - name: Remover refs de pull requests (se existirem)
        run: |
          cd lvgl-mirror
          git for-each-ref --format='%(refname)' | grep -E 'refs/(pull|changes|review)/' | while read ref; do
            echo "Removendo ref: $ref"
            git update-ref -d "$ref"
          done

      - name: Atualizar espelho com git fetch
        run: |
          cd lvgl-mirror
          git fetch origin
          #git remote update

      - name: Enviar branches e tags para repositório destino
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd lvgl-mirror
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/mrgouveia/mirror.git
          git push origin --all
          git push origin --tags
