name: Espelhar LVGL sem deletar main

on:
  schedule:
    - cron: '0 3 * * 0'  # Todo domingo às 03:00 UTC
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Clonar repositório LVGL com --mirror
        run: |
          git clone --mirror https://github.com/lvgl/lvgl.git lvgl-mirror

      - name: Remover refs ocultas (pull requests)
        run: |
          cd lvgl-mirror
          git for-each-ref --format='%(refname)' | grep 'refs/pull/' | while read ref; do
            echo "Removendo ref oculta: $ref"
            git update-ref -d "$ref"
          done

      - name: Limpar refspecs de push e tratar como bare
        run: |
          cd lvgl-mirror
          # Remove instruções herdadas que causam exclusão
          git config --unset-all remote.origin.push || true
          # Remove qualquer refspec perigosa
          git remote set-url origin https://github.com/lvgl/lvgl.git
          #git remote set-url --push origin https://x-access-token:${GH_TOKEN}@github.com/mrgouveia/mirror.git

      - name: Enviar branches e tags para repositório destino
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd lvgl-mirror
          git remote set-url --push origin https://x-access-token:${GH_TOKEN}@github.com/mrgouveia/mirror.git
          git push origin --all
          git push origin --tags
